// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Q7r2f-1tXeS91POQ84_tc5LvNmhPu-4',
    appId: '1:17214742206:web:1d72d106151eb7311888ef',
    messagingSenderId: '17214742206',
    projectId: 'filmout-5ac0a',
    authDomain: 'filmout-5ac0a.firebaseapp.com',
    storageBucket: 'filmout-5ac0a.appspot.com',
    measurementId: 'G-4NPL4H8KCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYkM630Qt-aFCArYn5J5vELFvtcASEKU',
    appId: '1:17214742206:android:db255dba931a5f9d1888ef',
    messagingSenderId: '17214742206',
    projectId: 'filmout-5ac0a',
    storageBucket: 'filmout-5ac0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdGy4hQnw076wuXG5CT9PlJX8GJvok-jg',
    appId: '1:17214742206:ios:02dee93bbea2e95b1888ef',
    messagingSenderId: '17214742206',
    projectId: 'filmout-5ac0a',
    storageBucket: 'filmout-5ac0a.appspot.com',
    iosClientId: '17214742206-g9ndpet5iiq6ah1ej9i36l45t3k0lep1.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdGy4hQnw076wuXG5CT9PlJX8GJvok-jg',
    appId: '1:17214742206:ios:bedbdd317b78cb6d1888ef',
    messagingSenderId: '17214742206',
    projectId: 'filmout-5ac0a',
    storageBucket: 'filmout-5ac0a.appspot.com',
    iosClientId: '17214742206-cf12ksq08d3b5e2s17beie169uvil2n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmout.RunnerTests',
  );
}
